# SPDX-License-Identifier: GPL-2.0
# 
# Copyright (c) 2022 Huawei Device Co., Ltd.
#
# Makefile for NewIP Hooks
#

ccflags-y += -I$(src)	# needed for trace events

obj-$(CONFIG_NEWIP_HOOKS) += nip_hooks.o
